services:
  db:
    image: mariadb:10.11
    container_name: userhub_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - userhub_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  postgres:
    image: postgres:17
    container_name: userhub_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - userhub_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ./userhub/backend
      dockerfile: Dockerfile
    container_name: userhub_api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PYTHONPATH: /app
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - userhub_network
    volumes:
      - ./userhub/backend:/app
    restart: on-failure
    command: ["sh", "-c", "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]

  frontend:
    build:
      context: ./userhub/frontend
      dockerfile: Dockerfile
    container_name: userhub_frontend
    env_file:
      - .env
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - api
    networks:
      - userhub_network
    volumes:
      - ./userhub/frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: userhub_nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - api
    networks:
      - userhub_network

volumes:
  db_data:
  postgres_data:

networks:
  userhub_network:
    driver: bridge
